server:
   port: 8083
   
spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:    config:      server:        git:          uri: https://github.com/mohddanishali/CLOUD-CONFIG-SERVER
          username: mohddanishali
          password: mohddanishali9759104535
          clone-on-start: true  profiles:    active: native